name: CMake build and test

on:
- push
- pull_request

jobs:
  build-ubuntu:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-16.04
        - ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: build
      run: cmake --build build
    - name: test
      run: env CTEST_OUTPUT_ON_FAILURE=1 cmake --build build --target test
