name: CMake build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ubuntu:

    name: ${{ matrix.os }} - ${{ matrix.cxx }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-20.04
        - ubuntu-22.04
        cxx:
        - g++
        - clang++
      fail-fast: false

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt-get install doxygen graphviz clang-tidy
    - name: Configure
      run: |
        mkdir build && cd build && \
          cmake \
          -D CMAKE_CXX_COMPILER=${{ matrix.cxx }} \
          -D CMAKE_BUILD_TYPE=Release \
          ..
    - name: Build
      run: cmake --build build
    - name: Test
      run: env CTEST_OUTPUT_ON_FAILURE=1 cmake --build build --target test
    - name: Documentation build test
      run: cmake --build build --target docs
