name: Cppcheck

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  cppcheck:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq cppcheck

      - name: Cppcheck
        run: |
          cppcheck --force --error-exitcode=2 --max-ctu-depth=4 --std c++11 --enable=all --inline-suppr --suppressions-list=.cppcheck_suppressions.txt -I include/ .
